seed: 42

agent:
  rollouts: 32
  experiment:
    directory: "PushBox"
    experiment_name: ""
    write_interval: 40 
    checkpoint_interval: 400 
    wandb: True             

trainer:
  timesteps: 1000000 



